name: HalfSurvival-1.19.2
version: '${project.version}'
main: halfSurvival.HalfSurvival
api-version: 1.19
authors: [ RedKiller ]

commands :
  test:
    description: test command
    aliases: [테스트]
    permission: HalfSurvivalSystem
    permission-message: 당신은 이 명령어를 사용할 권한이 존재하지 않습니다!

permissions:
  HalfSurvivalSystem:
    default: op
